apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  #  lables:
  #{{- include "spring.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
   matchLabels:
     app: ui
  template:
    metadata:
     labels:
      app: ui
    spec:
      containers:
        - name: container
          image: yanivomc/spring-music:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
