apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
  {{- include "spring.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
{{- include "spring.labels" . | nindent 4 }}

